<a href="https://colab.research.google.com/github/waj-ha/child-safety-fars-analysis/blob/main/notebooks/260606_ST_CASE_002.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analysis Enssential Tools and Libraries:
These libraries are essential tools for most data science workflows:

*   **NumPy**: Fundamental package for numerical computation, especially with arrays and matrices.
*   **Pandas**: Provides high-performance, easy-to-use data structures and data analysis tools (DataFrames).
*   **Matplotlib**: A comprehensive library for creating static, animated, and interactive visualizations.
*   **Seaborn**: Built on Matplotlib, it provides a high-level interface for drawing attractive and informative statistical graphics.
*   **Scikit-learn**: A robust machine learning library featuring various classification, regression, and clustering algorithms, along with tools for model selection and preprocessing.
*   **Statsmodels**: Provides classes and functions for the estimation of many different statistical models, as well as for conducting statistical tests and statistical data exploration.

The `!pip install` command is used to install Python packages. The `!` at the beginning tells Colab to run the command as a shell command. In this example, `numpy` is the name of the package to be installed.

In [2]:
common_data_science_libraries = [
    "numpy",        # Numerical operations
    "pandas",       # Data manipulation and analysis
    "matplotlib",   # Basic plotting
    "seaborn",      # Enhanced statistical data visualization
    "statsmodels",  # Statistical modeling
    "requests",     # HTTP requests for web data
]

# Install all listed libraries
!pip install {" ".join(common_data_science_libraries)}

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (0.14.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (1.16.3)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (1.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.5.20)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt # Import pyplot for plotting functions
import seaborn as sns
import sklearn
import tensorflow as tf

print(f"NumPy version: {np.__version__}")
print(f"Pandas version: {pd.__version__}")
print(f"Matplotlib version: {matplotlib.__version__}") # Access version from the main module
print(f"Seaborn version: {sns.__version__}")
print(f"Scikit-learn version: {sklearn.__version__}")
print(f"TensorFlow version: {tf.__version__}")

# You can add simple verification tests here if needed, for example:
# print(np.array([1, 2, 3]) + np.array([4, 5, 6]))
# print(pd.DataFrame({'A': [1, 2], 'B': [3, 4]}))

NumPy version: 2.0.2
Pandas version: 2.2.2
Matplotlib version: 3.10.0
Seaborn version: 0.13.2
Scikit-learn version: 1.6.1
TensorFlow version: 2.20.0

### Dataset Import Techniques
Raw data is placed at Github;

https://github.com/waj-ha/child-safety-fars-analysis.git

and accessed, and imported via Pandas Libraries. The files sizes are more than 100MB. So, these are

In [4]:
import pandas as pd
#url_accident = 'https://media.githubusercontent.com/media/waj-ha/child-safety-fars-analysis/refs/heads/main/data/raw/accident.csv'
#df_raw_accident = pd.read_csv(url_accident,encoding='unicode_escape', dtype=str, low_memory=False)
url_person = 'https://media.githubusercontent.com/media/waj-ha/child-safety-fars-analysis/refs/heads/main/data/raw/person.csv'
df_raw_person = pd.read_csv(url_person,encoding='unicode_escape', dtype=str, low_memory=False)
#url_vehicle = 'https://media.githubusercontent.com/media/waj-ha/child-safety-fars-analysis/refs/heads/main/data/raw/vehicle.csv'
#df_raw_vehicle = pd.read_csv(url_vehicle,encoding='unicode_escape', dtype=str, low_memory=False)

### EDA

In [5]:
def dataset_overview(df, dataset_name):
    print("*****************")
    print(f"{dataset_name} Dataset:")
    print("*****************")
    print("\nShape:", df.shape)
    print("\nCount:")
    print(df.nunique().sort_values(ascending=False))
    print("\nData Types:")
    print(df.dtypes.value_counts(ascending=False))
    print("\nDuplicates:", df.duplicated().sum())
    print(f"\nMissing Values Count:")
    missing_values = (df.isnull().sum().sort_values(ascending=False))
    non_zero_missing_values = missing_values[missing_values > 0]
    print(non_zero_missing_values)
    print(f"\nMissing Values Percentage:")
    missing_percentage = round(df.isnull().sum() * 100 / len(df), 2).sort_values(ascending=False)
    non_zero_missing_percentage = missing_percentage[missing_percentage > 0]
    print(non_zero_missing_percentage)
    print("\n---------------------------------------------------\n")

dataset_overview(df_raw_person, "Person")

*****************
Person Dataset:
*****************

Shape: (88326, 126)

Count:
ST_CASE          36297
VPICMODEL         2381
VPICMODELNAME     2325
DEATH_TM          1457
DEATH_TMNAME      1457
                 ...
EXTRICATNAME         3
FIRE_EXPNAME         2
FIRE_EXP             2
SCH_BUSNAME          2
SCH_BUS              2
Length: 126, dtype: int64

Data Types:
object    126
Name: count, dtype: int64

Duplicates: 0

Missing Values Count:
VPICMAKE             9020
MOD_YEAR             9020
VPICMODEL            9020
VPICMAKENAME         9020
MOD_YEARNAME         9020
FIRE_EXPNAME         9020
FIRE_EXP             9020
IMPACT1NAME          9020
IMPACT1              9020
ROLLOVERNAME         9020
ROLLOVER             9020
EMER_USENAME         9020
EMER_USE             9020
SPEC_USENAME         9020
SPEC_USE             9020
TOW_VEHNAME          9020
TOW_VEH              9020
GVWR_TONAME          9020
GVWR_TO              9020
GVWR_FROMNAME        9020
GVWR_FROM            9020
ICFINALBODYNAME      9020
ICFINALBODY          9020
BODY_TYPNAME         9020
BODY_TYP             9020
MAKENAME             9020
MAKE                 9020
VPICBODYCLASSNAME    9020
VPICBODYCLASS        9020
VPICMODELNAME        9020
MAK_MODNAME          9020
MAK_MOD              9020
dtype: int64

Missing Values Percentage:
VPICMAKE             10.21
MOD_YEAR             10.21
VPICMODEL            10.21
VPICMAKENAME         10.21
MOD_YEARNAME         10.21
FIRE_EXPNAME         10.21
FIRE_EXP             10.21
IMPACT1NAME          10.21
IMPACT1              10.21
ROLLOVERNAME         10.21
ROLLOVER             10.21
EMER_USENAME         10.21
EMER_USE             10.21
SPEC_USENAME         10.21
SPEC_USE             10.21
TOW_VEHNAME          10.21
TOW_VEH              10.21
GVWR_TONAME          10.21
GVWR_TO              10.21
GVWR_FROMNAME        10.21
GVWR_FROM            10.21
ICFINALBODYNAME      10.21
ICFINALBODY          10.21
BODY_TYPNAME         10.21
BODY_TYP             10.21
MAKENAME             10.21
MAKE                 10.21
VPICBODYCLASSNAME    10.21
VPICBODYCLASS        10.21
VPICMODELNAME        10.21
MAK_MODNAME          10.21
MAK_MOD              10.21
dtype: float64

---------------------------------------------------

Relevant Variables:

**`ST_CASE`**: Identify the crash case and Unique ID.

**`PER_NO`**: Identify the each person with Unique ID.

**`VEH_NO`**: Identify the vehicle with Unique ID.

**`AGE`**: Identify the age groups and risk difference.

**`SEX`**: Compare outcomes in males and females.

**`PER_TYP`**: Identify the type of perssenger. Occupant/Pedestrain.

**`RESTRAINT_USE`**: Compare the impact of use of restaint Systems and seatbelts.

**`SEAT_POS`**: Analyses seat position Effects.

**`INJ_SEV`**: Measure Crash outcomes.

**`BODY_TYP`**: Compare Vehicle types.

**`HOUR`**: Study Time of the day patterns.

**`WEATHER`**: Examine environmental conditions.

**`SPEEDING`**: Assess influence of speed related crashes

**`RURAL_URBAN`**: Compare rural or urban crash characteristics.

**`STATE`**: Compare the US states.

# `ST_CASE`:Consecutive Number (Primary Key)

This data element is the unique case number assigned to each crash. It appears on each data file
and is used to merge information from the data files together.

This data element is stored as a **numeric data element of six characters**;
the first two characters are the State code,
and the next four characters are case number with leading zeros if necessary.

[Fatality Analysis Reporting System Analytical User’s Manual, 1975-2024](https://github.com/waj-ha/child-safety-fars-analysis/blob/6c3be83f1700cb93c8d3a495211a92ccfd7aea08/references/Fatality%20Analysis%20Reporting%20System%20Analytical%20User%E2%80%99s%20Manual%2C%201975-2024.pdf)

(Page#31)

In [40]:
df_person_case = df_raw_person.copy()
df_person_case['ST_CASE'].unique(), df_person_case['ST_CASE'].duplicated().sum(), df_person_case['ST_CASE'].isnull().sum(), df_person_case['ST_CASE'].dtypes

(array(['10001', '10002', '10003', ..., '560100', '560101', '560102'],
       dtype=object),
 np.int64(52029),
 np.int64(0),
 dtype('O'))

In [41]:
counts = df_person_case['ST_CASE'].value_counts()
counts[counts > 5]

ST_CASE
480776    59
121482    46
280403    38
260959    35
481200    32
          ..
400037     6
410332     6
550331     6
560089     6
131302     6
Name: count, Length: 1644, dtype: int64

In [56]:
df_person_case[df_person_case['ST_CASE'] == '480776'].head(5)

,STATE,STATENAME,ST_CASE,VEH_NO,PER_NO,VE_FORMS,COUNTY,MONTH,MONTHNAME,DAY,...,DEVTYPE,DEVTYPENAME,DEVMOTOR,DEVMOTORNAME,LOCATION,LOCATIONNAME,WORK_INJ,WORK_INJNAME,HISPANIC,HISPANICNAME
74340,48,Texas,480776,1,1,4,21,3,March,22,...,96,Occupant of a Motor Vehicle,8,Occupant of a Motor Vehicle,0,Occupant of a Motor Vehicle,8,Not Applicable (not a fatality),0,Not A Fatality (not Applicable)
74341,48,Texas,480776,2,1,4,21,3,March,22,...,96,Occupant of a Motor Vehicle,8,Occupant of a Motor Vehicle,0,Occupant of a Motor Vehicle,8,Not Applicable (not a fatality),0,Not A Fatality (not Applicable)
74342,48,Texas,480776,2,2,4,21,3,March,22,...,96,Occupant of a Motor Vehicle,8,Occupant of a Motor Vehicle,0,Occupant of a Motor Vehicle,0,No,1,Mexican
74343,48,Texas,480776,2,3,4,21,3,March,22,...,96,Occupant of a Motor Vehicle,8,Occupant of a Motor Vehicle,0,Occupant of a Motor Vehicle,8,Not Applicable (not a fatality),0,Not A Fatality (not Applicable)
74344,48,Texas,480776,2,4,4,21,3,March,22,...,96,Occupant of a Motor Vehicle,8,Occupant of a Motor Vehicle,0,Occupant of a Motor Vehicle,8,Not Applicable (not a fatality),0,Not A Fatality (not Applicable)

# `PER_NO`:Person Number (Primary Key)

This data element is the consecutive number assigned to each person in the case (i.e., each
occupant, pedestrian, or non-motorists involved in the crash). This data element appears on each
person level data file and is used in conjunction with the ST_CASE data element (and sometimes
the VEH_NO data element) to merge information from person level data files.

[Fatality Analysis Reporting System Analytical User’s Manual, 1975-2024](https://github.com/waj-ha/child-safety-fars-analysis/blob/6c3be83f1700cb93c8d3a495211a92ccfd7aea08/references/Fatality%20Analysis%20Reporting%20System%20Analytical%20User%E2%80%99s%20Manual%2C%201975-2024.pdf)

(Page#33)

In [44]:
person_case_no = df_raw_person.copy()
person_case_no['PER_NO'].unique(), person_case_no['PER_NO'].duplicated().sum(), person_case_no['PER_NO'].isnull().sum(), person_case_no['PER_NO'].dtypes

(array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
        '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
        '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34',
        '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45',
        '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56'],
       dtype=object),
 np.int64(88270),
 np.int64(0),
 dtype('O'))

In [54]:
counts = person_case_no['PER_NO'].value_counts()
counts[counts > 0]

PER_NO
1     64493
2     15107
3      4844
4      2200
5       887
6       311
7       126
8        71
9        41
10       29
11       20
12       17
13       13
14       12
15       11
16       10
17        8
18        8
19        7
20        7
21        7
22        7
23        7
24        6
25        5
26        5
27        5
28        4
29        4
30        4
31        4
32        3
33        3
34        3
35        3
36        3
37        3
38        3
39        2
40        2
41        2
42        2
43        2
44        2
45        2
46        1
47        1
48        1
49        1
50        1
51        1
52        1
53        1
54        1
55        1
56        1
Name: count, dtype: int64

In [55]:
person_case_no[person_case_no['PER_NO'] == '56'].head(5)

,STATE,STATENAME,ST_CASE,VEH_NO,PER_NO,VE_FORMS,COUNTY,MONTH,MONTHNAME,DAY,...,DEVTYPE,DEVTYPENAME,DEVMOTOR,DEVMOTORNAME,LOCATION,LOCATIONNAME,WORK_INJ,WORK_INJNAME,HISPANIC,HISPANICNAME
74396,48,Texas,480776,2,56,4,21,3,March,22,...,96,Occupant of a Motor Vehicle,8,Occupant of a Motor Vehicle,0,Occupant of a Motor Vehicle,8,Not Applicable (not a fatality),0,Not A Fatality (not Applicable)

# `VEH_NO`:Vehicle Number (Primary Key)

This data element is the consecutive number assigned to each person in the case (i.e., each
occupant, pedestrian, or non-motorists involved in the crash). This data element appears on each
person level data file and is used in conjunction with the ST_CASE data element (and sometimes
the VEH_NO data element) to merge information from person level data files.

[Fatality Analysis Reporting System Analytical User’s Manual, 1975-2024](https://github.com/waj-ha/child-safety-fars-analysis/blob/6c3be83f1700cb93c8d3a495211a92ccfd7aea08/references/Fatality%20Analysis%20Reporting%20System%20Analytical%20User%E2%80%99s%20Manual%2C%201975-2024.pdf)

(Page#32)

In [57]:
person_case_no = df_raw_person.copy()
person_case_no['VEH_NO'].unique(), person_case_no['VEH_NO'].duplicated().sum(), person_case_no['VEH_NO'].isnull().sum(), person_case_no['VEH_NO'].dtypes

(array(['1', '0', '3', '2', '4', '5', '6', '7', '8', '9', '10', '11', '12',
        '13', '14', '15'], dtype=object),
 np.int64(88310),
 np.int64(0),
 dtype('O'))

In [58]:
counts = person_case_no['VEH_NO'].value_counts()
counts[counts > 0]

VEH_NO
1     49660
2     23865
0      9020
3      4039
4      1067
5       382
6       137
7        63
8        33
9        24
10       15
11        9
12        4
13        4
15        3
14        1
Name: count, dtype: int64

In [60]:
person_case_no[person_case_no['VEH_NO'] == '13'].head(5)

,STATE,STATENAME,ST_CASE,VEH_NO,PER_NO,VE_FORMS,COUNTY,MONTH,MONTHNAME,DAY,...,DEVTYPE,DEVTYPENAME,DEVMOTOR,DEVMOTORNAME,LOCATION,LOCATIONNAME,WORK_INJ,WORK_INJNAME,HISPANIC,HISPANICNAME
43607,26,Michigan,260959,13,1,15,65,11,November,2,...,96,Occupant of a Motor Vehicle,8,Occupant of a Motor Vehicle,0,Occupant of a Motor Vehicle,0,No,7,Non-Hispanic
43608,26,Michigan,260959,13,2,15,65,11,November,2,...,96,Occupant of a Motor Vehicle,8,Occupant of a Motor Vehicle,0,Occupant of a Motor Vehicle,0,No,7,Non-Hispanic
43609,26,Michigan,260959,13,3,15,65,11,November,2,...,96,Occupant of a Motor Vehicle,8,Occupant of a Motor Vehicle,0,Occupant of a Motor Vehicle,0,No,7,Non-Hispanic
65149,42,Pennsylvania,420224,13,1,13,133,4,April,16,...,96,Occupant of a Motor Vehicle,8,Occupant of a Motor Vehicle,0,Occupant of a Motor Vehicle,8,Not Applicable (not a fatality),0,Not A Fatality (not Applicable)

In [71]:
person_case_no[['ST_CASE','PER_NO','VEH_NO']].duplicated().sum(),
person_case_no[['ST_CASE','PER_NO','VEH_NO']].isnull().sum(), person_case_no[['ST_CASE','PER_NO','VEH_NO']].dtypes

(ST_CASE    0
 PER_NO     0
 VEH_NO     0
 dtype: int64,
 ST_CASE    object
 PER_NO     object
 VEH_NO     object
 dtype: object)

In [72]:
print(person_case_no.shape)
person_case_no.head(5)

(88326, 126)

,STATE,STATENAME,ST_CASE,VEH_NO,PER_NO,VE_FORMS,COUNTY,MONTH,MONTHNAME,DAY,...,DEVTYPE,DEVTYPENAME,DEVMOTOR,DEVMOTORNAME,LOCATION,LOCATIONNAME,WORK_INJ,WORK_INJNAME,HISPANIC,HISPANICNAME
0,1,Alabama,10001,1,1,1,125,1,January,1,...,96,Occupant of a Motor Vehicle,8,Occupant of a Motor Vehicle,0,Occupant of a Motor Vehicle,0,No,7,Non-Hispanic
1,1,Alabama,10002,1,1,1,73,1,January,2,...,96,Occupant of a Motor Vehicle,8,Occupant of a Motor Vehicle,0,Occupant of a Motor Vehicle,0,No,7,Non-Hispanic
2,1,Alabama,10003,0,1,1,3,1,January,2,...,0,Not Applicable,0,Not Applicable,11,"Not at Intersection - On Roadway, Not in Marke...",0,No,7,Non-Hispanic
3,1,Alabama,10003,1,1,1,3,1,January,2,...,96,Occupant of a Motor Vehicle,8,Occupant of a Motor Vehicle,0,Occupant of a Motor Vehicle,8,Not Applicable (not a fatality),0,Not A Fatality (not Applicable)
4,1,Alabama,10003,1,2,1,3,1,January,2,...,96,Occupant of a Motor Vehicle,8,Occupant of a Motor Vehicle,0,Occupant of a Motor Vehicle,8,Not Applicable (not a fatality),0,Not A Fatality (not Applicable)

In [82]:
def primary_key_check(df):
  duplicates = df.duplicated().sum()
  missing_values = df.isnull().sum().sum()
  data_types = df.dtypes.value_counts()
  print(f"Duplicates: {duplicates}")
  print(f"Missing Values: {missing_values}")

  if duplicates == 0 & missing_values == 0:
    print("Primay Key Check:PASSED")
  else:
    print("Primary Key Check: FAILED")

primary_key_check(person_case_no[['ST_CASE']])

Duplicates: 52029
Missing Values: 0
Primary Key Check: FAILED

# `AGE`
This data element identifies the person’s age in years on the date of the crash.
According to reference manual, the valid age is between 0-120.

[Fatality Analysis Reporting System Analytical User’s Manual, 1975-2024](https://github.com/waj-ha/child-safety-fars-analysis/blob/6c3be83f1700cb93c8d3a495211a92ccfd7aea08/references/Fatality%20Analysis%20Reporting%20System%20Analytical%20User%E2%80%99s%20Manual%2C%201975-2024.pdf)

(Page#296)

In [20]:
df_person_age = df_raw_person.copy()
df_person_age['AGE'].unique(),df_person_age.duplicated().sum(), df_person_age.shape, df_person_age['AGE'].isna().sum(), df_person_age['AGE'].dtypes

(array(['50', '42', '47', '23', '19', '60', '66', '31', '28', '25', '48',
        '999', '45', '29', '53', '15', '62', '16', '998', '22', '24', '46',
        '65', '39', '40', '59', '32', '70', '52', '54', '68', '33', '58',
        '27', '44', '37', '71', '34', '35', '8', '11', '30', '57', '55',
        '36', '61', '17', '49', '63', '21', '74', '72', '56', '20', '77',
        '38', '78', '18', '73', '43', '14', '75', '41', '67', '82', '87',
        '51', '69', '26', '79', '85', '7', '13', '4', '76', '90', '3',
        '12', '5', '6', '10', '81', '89', '64', '80', '2', '84', '83', '1',
        '9', '86', '0', '88', '94', '93', '91', '95', '97', '96', '92',
        '101', '98', '99', '100'], dtype=object),
 np.int64(0),
 (88326, 126),
 np.int64(0),
 dtype('O'))

From FARS reference manual, we know the outliers are defined with special codes. For **`AGE`** these code are,

*   `998` = Unknow
*   `999` = Not Reported

To get the real age distribution, rows with these codes should be removed.

In [81]:
primary_key_check(df_person_age['AGE'])

Duplicates in 'AGE': 88222
Missing Values in 'AGE': 0
Primary Key Check for 'AGE': FAILED

# NaN Method

In [ ]:
df_person_age_m1 = df_person_age.replace(['998', '999'], np.nan)
df_person_age_m1['AGE'].unique()

In [ ]:
# convert dtype to float64 usinfg coerce.
df_person_age_m1_numeric = pd.to_numeric(df_person_age_m1['AGE'], errors='coerce')

In [ ]:
df_person_age_m1_numeric.unique(), df_person_age_m1_numeric.dtype,
df_person_age_m1_numeric.shape, df_person_age_m1_numeric.isna().sum()

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))

plt.hist(df_person_age_m1_numeric.dropna(), bins=100)

plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')

plt.show()

# Method Data Frame Manipolation

In [ ]:
df_person_age_m2 = df_raw_person.copy()
df_person_age_m2 = df_person_age_m2[df_person_age_m2['AGE'] != '998']
df_person_age_m2 = df_person_age_m2[df_person_age_m2['AGE'] != '999']
df_person_age_m2['AGE'] = pd.to_numeric(df_person_age_m2['AGE'])
df_person_age_m2.shape
df_person_age_m2['AGE'].unique()

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))

plt.hist(df_person_age_m2['AGE'], bins=100)

plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')

In [ ]:
age = df_person_age_m2['AGE']

plt.figure(figsize=(10,5))

plt.hist(
    age,
    bins=100,
    density=True,
    alpha=0.5
)

age.plot(kind='density')

plt.title('Age Distribution with Density Curve')
plt.xlabel('Age')

plt.show()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
sns.histplot(age, bins=100, kde=True)

plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency / Density')

plt.show()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
sns.histplot(age, bins=range(-1,101,5), kde=True)

plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency / Density')

plt.show()
age.describe()

In [ ]:
round(age.mean(), 2), age.median(), round(age.std(), 2), age.min(), age.max(), age.quantile(0.25), age.quantile(0.75)

**Mean Age (rounded to 2 decimal places)**: 40.61

**Median Age:** 38.0

**Standard Deviation of Age:** 20.41

**Minimum Age:** 0

**Maximum Age:** 101

**25th Percentile (Q1) of Age:** 24.0

**75th Percentile (Q3) of Age:** 56.0

In [83]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
sns.histplot(age, bins=range(-1,101,5), kde=True)

mean_age = age.mean()
mode_age = age.mode()[0] # Get the first mode if there are multiple
median_age = age.median()
std_age = age.std()

plt.axvline(mean_age, color='red', linestyle='--', label=f'Mean Age: {mean_age:.2f}', linewidth=3)
plt.axvline(mode_age, color='blue', linestyle=':', label=f'Mode Age: {mode_age:.0f}', linewidth=3)
plt.axvline(median_age, color='green', linestyle='-.', label=f'Median Age: {median_age:.0f}', linewidth=3)
plt.axvline(mean_age - std_age, color='purple', linestyle='-.', label=f'-1 Std Dev: {(mean_age - std_age):.2f}', linewidth=3)
plt.axvline(mean_age + std_age, color='purple', linestyle='-.', label=f'+1 Std Dev: {(mean_age + std_age):.2f}', linewidth=3)
plt.legend()

plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency / Density')

plt.show()
age.describe()

NameError: name 'age' is not defined

**Shape of the Distribution:** The histogram shows that the distribution of ages is right-skewed, meaning there's a longer tail towards older ages. The density curve (KDE) also confirms this shape, peaking at a younger age and gradually declining.

**Central Tendency:**
The mean age is approximately 40.61 years, and the median age is 38.0 years. The fact that the mean is slightly higher than the median is consistent with a right-skewed distribution, as the higher ages pull the mean towards the right.
The mode age is 20 years, indicating that this is the most frequently occurring age in the dataset.

**Spread of the Data:**
The standard deviation is about 20.41 years, which suggests a considerable spread in the ages. The lines for +/- 1 standard deviation around the mean show how much the data typically varies.
A significant portion of the data (approximately 50%) falls between the 25th percentile (Q1) of 24.0 years and the 75th percentile (Q3) of 56.0 years.

**Range of Ages:** The ages range from a minimum of 0 years to a maximum of 101 years, which aligns with the valid age range mentioned in the FARS reference manual (0-120).

In summary, the data primarily consists of individuals in their 20s to 50s, with a notable peak around 20 years old. There's a wide range of ages, but fewer individuals are represented at very old ages.

In [ ]:
skewness = age.skew()
print(f"Skewness of the age distribution: {skewness:.2f}")

The skewness value of approximately 0.43 confirms that the age distribution is **right-skewed** (positively skewed). This means the tail of the distribution extends more to the right, towards higher ages, as we observed in the plot where the mean is greater than the median.

1. **Mean (Arithmetic Mean):** The mean is the sum of all values in a dataset divided by the number of values. It's often denoted by
$\mu$$\mu$ (for a population) or $\bar{x}$$\bar{x}$ (for a sample).

Formula:
[\bar{x} = \frac{\sum_{i=1}^{n} x_i}{n}\]

 Where:

$\sum x_i$$\sum x_i$ is the sum of all observations.

$n$$n$ is the number of observations.

2. **Mode:** The mode is the value that appears most frequently in a dataset. A dataset can have one mode (unimodal), multiple modes (multimodal), or no mode if all values appear with the same frequency.

Formula: There isn't a single mathematical formula for the mode, as it's determined by counting frequencies. You typically find the value(s) with the highest frequency.

3. **First Quartile (Q1):** Q1 is the median of the lower half of the data. It represents the 25th percentile, meaning 25% of the data falls below this value.

Formula: To find Q1:

Arrange the data in ascending order.
Find the median of the entire dataset. (If $n$$n$ is odd, exclude the median from the lower half; if $n$$n$ is even, split the data evenly).
Q1 is the median of the values below the overall median.

4. **Third Quartile (Q3)**: Q3 is the median of the upper half of the data. It represents the 75th percentile, meaning 75% of the data falls below this value.

Formula: To find Q3:

Arrange the data in ascending order.
Find the median of the entire dataset.
Q3 is the median of the values above the overall median.

5. **Standard Deviation:** The standard deviation measures the average amount of variability or dispersion around the mean. A low standard deviation indicates that data points tend to be close to the mean, while a high standard deviation indicates that data points are spread out over a wider range of values.

Formula (for a sample, denoted by $s$$s$):

 [ s = \sqrt{\frac{\sum_{i=1}^{n} (x_i - \bar{x})^2}{n-1}} ]

 Formula (for a population, denoted by $\sigma$$\sigma$):

  [ \sigma = \sqrt{\frac{\sum_{i=1}^{N} (x_i - \mu)^2}{N}} ]
  
  Where:

$x_i$$x_i$ is each individual data point.
$\bar{x}$$\bar{x}$ (sample mean) or $\mu$$\mu$ (population mean) is the mean of the dataset.
$n$$n$ (sample size) or $N$$N$ (population size) is the number of data points.

6.** Skewness:** Skewness is a measure of the asymmetry of the probability distribution of a real-valued random variable about its mean. It indicates the direction and magnitude of a distribution's deviation from horizontal symmetry.

Formula (sample skewness, often using Pearson's second coefficient of skewness or moment coefficient of skewness):

**Pearson's Second Coefficient of Skewness:**

[ Skewness = \frac{3 \times (Mean - Median)}{Standard\ Deviation} ]

**Moment Coefficient of Skewness (more commonly used in software like pandas)**:

 [ g_1 = \frac{n}{(n-1)(n-2)} \sum_{i=1}^{n} \left( \frac{x_i - \bar{x}}{s} \right)^3 ]

 (This is one common form for sample skewness, adjusted for bias. Other definitions exist.)

Where:

$x_i$$x_i$ is each individual data point.
$\bar{x}$$\bar{x}$ is the sample mean.
$s$$s$ is the sample standard deviation.
$n$$n$ is the number of observations.